# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e11ed1bb5bca1b0d04681943c0aa0f5e865d5ca4e3f501dca7aee7fd10d0ec9a88c0b9bb02ce9b7a00a4717b2eed9ddbead7256922166d4485429c1f6e76f610

test:
  secret_key_base: e97237331cd69fca2e7162c60d91766c35d8adb0cc8f9e2b5c1bc68ce13181a6355983b891aee2ad1279f3d15564d0c006cfa46cc900b8e2b8478bef18ee5a39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
